CREATE TABLE "unidade_federativa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "municipio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "unidade_federativa_id" integer
);

CREATE TABLE "unidade_cooperativa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "municipio_id" integer
);

CREATE TABLE "classificacao_cooperado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "desconto" numeric
);

CREATE TABLE "tipo_cooperado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "cooperado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "tipo_cooperado_id" integer,
  "classificacao_cooperado_id" integer
);

CREATE TABLE "estado_civil" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "pessoa_fisica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpf" varchar,
  "rg" varchar,
  "estado_civil_id" integer,
  "data_nascimento" timestamptz,
  "cooperado_id" integer
);

CREATE TABLE "pessoa_juridica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "data_fundacao" timestamptz,
  "cooperado_id" integer
);

CREATE TABLE "socio_pessoa_juridica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" varchar,
  "estado_civil_id" integer,
  "data_nascimento" timestamptz,
  "pessoa_juridica_id" integer
);

CREATE TABLE "grupo_produto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar
);

CREATE TABLE "produto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "principio_ativo" varchar,
  "unidade_medida" varchar,
  "valor_venda" numeric,
  "grupo_produto_id" integer
);

CREATE TABLE "venda_produto" (
  "produto_id" integer,
  "venda_id" integer,
  "quantidade" integer,
  PRIMARY KEY ("produto_id", "venda_id")
);

CREATE TABLE "venda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cooperado_id" integer,
  "data_compra" timestamptz,
  "data_vencimento" timestamptz,
  "valor_venda" numeric,
  "valor_icms" numeric,
  "valor_desconto" numeric,
  "valor_juros" numeric,
  "porcentagem_desconto" numeric,
  "porcentagem_juros" numeric,
  "porcentagem_icms" numeric,
  "valor_total" numeric
);

ALTER TABLE "municipio" ADD FOREIGN KEY ("unidade_federativa_id") REFERENCES "unidade_federativa" ("id");

ALTER TABLE "unidade_cooperativa" ADD FOREIGN KEY ("municipio_id") REFERENCES "municipio" ("id");

ALTER TABLE "cooperado" ADD FOREIGN KEY ("tipo_cooperado_id") REFERENCES "tipo_cooperado" ("id");

ALTER TABLE "cooperado" ADD FOREIGN KEY ("classificacao_cooperado_id") REFERENCES "classificacao_cooperado" ("id");

ALTER TABLE "pessoa_fisica" ADD FOREIGN KEY ("estado_civil_id") REFERENCES "estado_civil" ("id");

ALTER TABLE "pessoa_fisica" ADD FOREIGN KEY ("cooperado_id") REFERENCES "cooperado" ("id");

ALTER TABLE "pessoa_juridica" ADD FOREIGN KEY ("cooperado_id") REFERENCES "cooperado" ("id");

ALTER TABLE "socio_pessoa_juridica" ADD FOREIGN KEY ("estado_civil_id") REFERENCES "estado_civil" ("id");

ALTER TABLE "socio_pessoa_juridica" ADD FOREIGN KEY ("pessoa_juridica_id") REFERENCES "pessoa_juridica" ("id");

ALTER TABLE "produto" ADD FOREIGN KEY ("grupo_produto_id") REFERENCES "grupo_produto" ("id");

ALTER TABLE "venda_produto" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id");

ALTER TABLE "venda_produto" ADD FOREIGN KEY ("venda_id") REFERENCES "venda" ("id");

ALTER TABLE "venda" ADD FOREIGN KEY ("cooperado_id") REFERENCES "cooperado" ("id");

INSERT INTO "unidade_federativa" ("nome") VALUES ('Paraná');
INSERT INTO "unidade_federativa" ("nome") VALUES ('Santa Catarina');
INSERT INTO "unidade_federativa" ("nome") VALUES ('Mato Grosso do Sul');
INSERT INTO "municipio" ("nome", "unidade_federativa_id") VALUES ('Campo Mourão', 1), ('Curitiba', 1);
INSERT INTO "municipio" ("nome", "unidade_federativa_id") VALUES ('Florianópolis', 2), ('Joinville', 2);
INSERT INTO "municipio" ("nome", "unidade_federativa_id") VALUES ('Campo Grande', 3), ('Dourados', 3);
INSERT INTO "unidade_cooperativa" ("nome", "municipio_id") VALUES ('Cooperativa Campo Mourão', 1), ('Cooperativa Curitiba', 2);
INSERT INTO "unidade_cooperativa" ("nome", "municipio_id") VALUES ('Cooperativa Florianópolis', 3), ('Cooperativa Joinville', 4);
INSERT INTO "unidade_cooperativa" ("nome", "municipio_id") VALUES ('Cooperativa Campo Grande', 5), ('Cooperativa Dourados', 6);
INSERT INTO "classificacao_cooperado" ("nome","desconto") VALUES ('A','0.05'), ('B', '0.03'), ('C', '0.0');
INSERT INTO "tipo_cooperado" ("nome") VALUES ('Pessoa Física'), ('Pessoa Jurídica');
INSERT INTO "estado_civil" ("nome") VALUES ('Solteiro'), ('Casado'), ('Divorciado');
INSERT INTO "cooperado" ("nome", "tipo_cooperado_id", "classificacao_cooperado_id") VALUES ('Cooperado 1', 1, 1), ('Cooperado 2', 1, 2), ('Cooperado 3', 1, 3), ('Cooperado 4', 2, 1), ('Cooperado 5', 2, 2), ('Cooperado 6', 2, 3);
INSERT INTO "grupo_produto" ("nome") VALUES ('Fertilizantes'), ('Corretivos'), ('Herbicidas'), ('Fungicidas'), ('Inseticidas');
INSERT INTO "produto" ("nome", "principio_ativo", "unidade_medida", "valor_venda", "grupo_produto_id") VALUES ('Uréia', 'Nitrogênio', 'Kg', 100, 1), ('Calcário', 'Calcário', 'Kg', 50, 2), ('Glifosato', 'Glifosato', 'Kg', 200, 3), ('Mancozeb', 'Mancozeb', 'Kg', 150, 4), ('Clorpirifós', 'Clorpirifós', 'Kg', 250, 5);
INSERT INTO "pessoa_fisica" ("cpf", "rg", "estado_civil_id", "data_nascimento", "cooperado_id") VALUES ('12345678901', '1234567', 1, '1990-01-01', 1), ('12345678902', '1234568', 2, '1991-01-01', 2), ('12345678903', '1234569', 3, '1992-01-01', 3);
INSERT INTO "pessoa_juridica" ("nome", "data_fundacao", "cooperado_id") VALUES ('Empresa 1', '1990-01-01', 4), ('Empresa 2', '1991-01-01', 5), ('Empresa 3', '1992-01-01', 6);
INSERT INTO "socio_pessoa_juridica" ("documento", "estado_civil_id", "data_nascimento", "pessoa_juridica_id") VALUES ('12345678904', 1, '1990-01-01', 1), ('12345678905', 2, '1991-01-01', 2), ('12345678906', 3, '1992-01-01', 3);
